# Generated by Django 4.1 on 2022-09-12 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='action',
            old_name='TaskTitle',
            new_name='Title',
        ),
    ]
