# Generated by Django 4.1 on 2022-09-12 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_tasktitle_action_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='action',
            old_name='Title',
            new_name='title',
        ),
    ]
